# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07742069613f13c7342a7d36487df2364054bf81502eeb15791436aed75d81f096292475136f0fc087ec15abb94e47fc297b2dbbde85db55b6903dbc9e9d8018

test:
  secret_key_base: 3442160cd1cd6ece449533969b9c56bfb766ffe3e3462ed46b80c06cab6608c1ea62b4fddf71505500fa9936a68a419ba2f8fdffd476a6cc4a74ef4c1696a640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
